use_frameworks!

target 'SQLManager_Example' do
  pod 'SQLManager', :path => '../'

  target 'SQLManager_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
    pod 'FMDB' , '2.6.2'
  end
end
